import {
  School,
  User,
  Vehicle,
  Route,
  Driver,
  Aide,
  Parent,
  Student,
  TripHistoryItem,
  Subscription,
  Invoice,
} from "@/types/dashboard";

export const initialSchools: School[] = [
  {
    id: "sch-1",
    name: "Lincoln International School",
    address: "742 Evergreen Terrace, Chicago, IL 60614",
    contactEmail: "transport@lincoln.edu",
    contactPhone: "+1 (312) 555-0192",
    adminName: "Dr. Julian Hayes",
    adminEmail: "j.hayes@lincoln.edu",
    plan: "Enterprise",
    status: "active",
    studentsCount: 348,
    vehiclesCount: 8,
    routesCount: 6,
    usersCount: 6,
    createdAt: "2025-08-15",
  },
  {
    id: "sch-2",
    name: "St. Jude Collegiate Academy",
    address: "1200 Beacon St, Boston, MA 02116",
    contactEmail: "ops@stjude.edu",
    contactPhone: "+1 (617) 555-0144",
    adminName: "Sister Katherine Moore",
    adminEmail: "k.moore@stjude.edu",
    plan: "Growth",
    status: "active",
    studentsCount: 215,
    vehiclesCount: 5,
    routesCount: 4,
    usersCount: 4,
    createdAt: "2025-09-01",
  },
  {
    id: "sch-3",
    name: "Oakwood Day Preparatory",
    address: "45 Valley View Road, Austin, TX 78746",
    contactEmail: "mobility@oakwoodprep.org",
    contactPhone: "+1 (512) 555-0178",
    adminName: "Dean Arthur Vance",
    adminEmail: "a.vance@oakwoodprep.org",
    plan: "Growth",
    status: "active",
    studentsCount: 190,
    vehiclesCount: 4,
    routesCount: 3,
    usersCount: 3,
    createdAt: "2025-10-12",
  },
  {
    id: "sch-4",
    name: "Horizon STEAM Charter",
    address: "88 Innovation Way, Seattle, WA 98109",
    contactEmail: "admin@horizonsteam.org",
    contactPhone: "+1 (206) 555-0189",
    adminName: "Tanya Albright",
    adminEmail: "t.albright@horizonsteam.org",
    plan: "Starter",
    status: "trial",
    studentsCount: 85,
    vehiclesCount: 2,
    routesCount: 2,
    usersCount: 2,
    createdAt: "2026-01-10",
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: "veh-1",
    vehicleNumber: "BUS-104",
    registrationNumber: "IL-TR-8492",
    type: "Full Bus (72 pax)",
    capacity: 72,
    model: "Blue Bird Vision Clean Diesel",
    year: 2024,
    assignedDriverId: "drv-1",
    assignedDriverName: "Ahmed Khan",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    schoolId: "sch-1",
    status: "on_route",
    currentLocation: {
      lat: 41.8819,
      lng: -87.6278,
      name: "Grand Ave & Elm St",
    },
    speedMph: 24,
    studentsOnboard: 18,
    eta: "7:42 AM",
    lastUpdated: "Just now",
  },
  {
    id: "veh-2",
    vehicleNumber: "BUS-108",
    registrationNumber: "IL-TR-9102",
    type: "Full Bus (72 pax)",
    capacity: 72,
    model: "Thomas Built Saf-T-Liner C2",
    year: 2023,
    assignedDriverId: "drv-2",
    assignedDriverName: "Marcus Vance",
    assignedRouteId: "rt-2",
    assignedRouteName: "Route 04 · North Loop",
    schoolId: "sch-1",
    status: "on_route",
    currentLocation: {
      lat: 41.895,
      lng: -87.641,
      name: "West Gate Crossing",
    },
    speedMph: 19,
    studentsOnboard: 24,
    eta: "7:48 AM",
    lastUpdated: "1 min ago",
  },
  {
    id: "veh-3",
    vehicleNumber: "BUS-101",
    registrationNumber: "IL-TR-7611",
    type: "Mid Bus (36 pax)",
    capacity: 36,
    model: "IC Bus CE Series",
    year: 2022,
    assignedDriverId: "drv-3",
    assignedDriverName: "Elena Rostova",
    assignedRouteId: "rt-3",
    assignedRouteName: "Route 01 · South Hill",
    schoolId: "sch-1",
    status: "at_stop",
    currentLocation: {
      lat: 41.862,
      lng: -87.618,
      name: "Oakridge Terrace Stop #4",
    },
    speedMph: 0,
    studentsOnboard: 14,
    eta: "7:55 AM",
    lastUpdated: "2 mins ago",
  },
  {
    id: "veh-4",
    vehicleNumber: "BUS-112",
    registrationNumber: "IL-TR-4509",
    type: "Full Bus (72 pax)",
    capacity: 72,
    model: "Blue Bird All American",
    year: 2021,
    assignedDriverId: "drv-4",
    assignedDriverName: "David Miller",
    assignedRouteId: "rt-4",
    assignedRouteName: "Route 12 · Highland Park",
    schoolId: "sch-1",
    status: "delayed",
    currentLocation: {
      lat: 41.91,
      lng: -87.65,
      name: "Fullerton Pkwy (Traffic delay)",
    },
    speedMph: 8,
    studentsOnboard: 22,
    eta: "8:04 AM (+6 min)",
    lastUpdated: "Just now",
  },
  {
    id: "veh-5",
    vehicleNumber: "VAN-201",
    registrationNumber: "IL-TR-2231",
    type: "Minivan (14 pax)",
    capacity: 14,
    model: "Ford Transit Passenger 350",
    year: 2024,
    assignedDriverId: "drv-5",
    assignedDriverName: "Sarah Jenkins",
    assignedRouteId: "rt-5",
    assignedRouteName: "Route 14 · East Meadow",
    schoolId: "sch-1",
    status: "active",
    currentLocation: {
      lat: 41.875,
      lng: -87.62,
      name: "School Depot Yard",
    },
    speedMph: 0,
    studentsOnboard: 0,
    eta: "Depot standby",
    lastUpdated: "5 mins ago",
  },
  {
    id: "veh-6",
    vehicleNumber: "EV-301",
    registrationNumber: "IL-EV-1004",
    type: "EV Shuttle (24 pax)",
    capacity: 24,
    model: "Lion Electric LionC Zero Emission",
    year: 2025,
    assignedDriverId: "drv-6",
    assignedDriverName: "Carlos Mendez",
    assignedRouteId: undefined,
    schoolId: "sch-1",
    status: "maintenance",
    currentLocation: {
      lat: 41.87,
      lng: -87.63,
      name: "Midwest EV Service Hub",
    },
    speedMph: 0,
    studentsOnboard: 0,
    eta: "Scheduled battery inspection",
    lastUpdated: "12 mins ago",
  },
  {
    id: "veh-7",
    vehicleNumber: "BUS-115",
    registrationNumber: "IL-TR-3390",
    type: "Full Bus (72 pax)",
    capacity: 72,
    model: "Thomas Built Saf-T-Liner",
    year: 2020,
    assignedDriverId: undefined,
    assignedRouteId: undefined,
    schoolId: "sch-1",
    status: "inactive",
    currentLocation: {
      lat: 41.875,
      lng: -87.62,
      name: "North Lot Reserve",
    },
    speedMph: 0,
    studentsOnboard: 0,
    eta: "Off duty",
    lastUpdated: "1 hour ago",
  },
  {
    id: "veh-8",
    vehicleNumber: "VAN-204",
    registrationNumber: "IL-TR-5561",
    type: "Minivan (14 pax)",
    capacity: 14,
    model: "Mercedes-Benz Sprinter 2500",
    year: 2023,
    assignedDriverId: undefined,
    assignedRouteId: undefined,
    schoolId: "sch-1",
    status: "active",
    currentLocation: {
      lat: 41.875,
      lng: -87.62,
      name: "North Lot Reserve",
    },
    speedMph: 0,
    studentsOnboard: 0,
    eta: "Ready for afternoon run",
    lastUpdated: "15 mins ago",
  },
];

export const initialRoutes: Route[] = [
  {
    id: "rt-1",
    routeNumber: "Route 08",
    name: "West Valley Corridor",
    schoolId: "sch-1",
    assignedVehicleId: "veh-1",
    assignedVehicleNumber: "BUS-104",
    assignedDriverId: "drv-1",
    assignedDriverName: "Ahmed Khan",
    assignedAideId: "aid-1",
    assignedAideName: "Maria Santos",
    studentsCount: 28,
    stopsCount: 6,
    startTime: "07:15 AM",
    expectedArrival: "07:55 AM",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "in_progress",
    description: "Main thoroughfare connecting West Valley communities directly to campus North Gate.",
    stops: [
      { id: "st-1", name: "Maple Ave & 4th", address: "402 Maple Ave", scheduledTime: "07:18 AM", studentsCount: 5, status: "departed", order: 1, lat: 41.88, lng: -87.64 },
      { id: "st-2", name: "Cedar Hill Community Center", address: "128 Cedar Hill Rd", scheduledTime: "07:25 AM", studentsCount: 6, status: "departed", order: 2, lat: 41.883, lng: -87.635 },
      { id: "st-3", name: "West Gate Crossing", address: "890 West Gate Blvd", scheduledTime: "07:33 AM", studentsCount: 7, status: "reached", order: 3, lat: 41.886, lng: -87.63 },
      { id: "st-4", name: "Grand Ave & Elm St", address: "1405 Grand Ave", scheduledTime: "07:42 AM", studentsCount: 4, status: "upcoming", order: 4, lat: 41.889, lng: -87.625 },
      { id: "st-5", name: "River Oaks Roundabout", address: "220 River Oaks Dr", scheduledTime: "07:49 AM", studentsCount: 6, status: "upcoming", order: 5, lat: 41.892, lng: -87.62 },
      { id: "st-6", name: "Lincoln School — Main Portico", address: "742 Evergreen Terrace", scheduledTime: "07:55 AM", studentsCount: 0, status: "upcoming", order: 6, lat: 41.895, lng: -87.615 },
    ],
  },
  {
    id: "rt-2",
    routeNumber: "Route 04",
    name: "North Loop Express",
    schoolId: "sch-1",
    assignedVehicleId: "veh-2",
    assignedVehicleNumber: "BUS-108",
    assignedDriverId: "drv-2",
    assignedDriverName: "Marcus Vance",
    assignedAideId: "aid-2",
    assignedAideName: "Brenda Walsh",
    studentsCount: 32,
    stopsCount: 5,
    startTime: "07:10 AM",
    expectedArrival: "07:50 AM",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "in_progress",
    description: "Serves Northern suburban subdivisions and transfer stops.",
    stops: [
      { id: "st-21", name: "Pinewood Estates", address: "550 Pinewood Rd", scheduledTime: "07:15 AM", studentsCount: 8, status: "departed", order: 1 },
      { id: "st-22", name: "Lakeland Library", address: "1020 Lake Blvd", scheduledTime: "07:26 AM", studentsCount: 9, status: "departed", order: 2 },
      { id: "st-23", name: "Fairview Park East", address: "310 Fairview Ave", scheduledTime: "07:36 AM", studentsCount: 8, status: "upcoming", order: 3 },
      { id: "st-24", name: "Highland Heights", address: "90 Highland Dr", scheduledTime: "07:44 AM", studentsCount: 7, status: "upcoming", order: 4 },
      { id: "st-25", name: "Lincoln School — North Gate", address: "742 Evergreen Terrace", scheduledTime: "07:50 AM", studentsCount: 0, status: "upcoming", order: 5 },
    ],
  },
  {
    id: "rt-3",
    routeNumber: "Route 01",
    name: "South Hill Neighborhood",
    schoolId: "sch-1",
    assignedVehicleId: "veh-3",
    assignedVehicleNumber: "BUS-101",
    assignedDriverId: "drv-3",
    assignedDriverName: "Elena Rostova",
    assignedAideId: "aid-3",
    assignedAideName: "James Lee",
    studentsCount: 20,
    stopsCount: 4,
    startTime: "07:20 AM",
    expectedArrival: "07:58 AM",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "in_progress",
    description: "Dense neighborhood route with frequent safe street-corner pickups.",
    stops: [
      { id: "st-31", name: "Brookside Commons", address: "12 Brookside Way", scheduledTime: "07:24 AM", studentsCount: 6, status: "departed", order: 1 },
      { id: "st-32", name: "Oakridge Terrace", address: "400 Oakridge Rd", scheduledTime: "07:34 AM", studentsCount: 5, status: "departed", order: 2 },
      { id: "st-33", name: "South Valley Plaza", address: "810 S Valley Pkwy", scheduledTime: "07:45 AM", studentsCount: 9, status: "reached", order: 3 },
      { id: "st-34", name: "Lincoln School — South Loop", address: "742 Evergreen Terrace", scheduledTime: "07:58 AM", studentsCount: 0, status: "upcoming", order: 4 },
    ],
  },
  {
    id: "rt-4",
    routeNumber: "Route 12",
    name: "Highland Park Connector",
    schoolId: "sch-1",
    assignedVehicleId: "veh-4",
    assignedVehicleNumber: "BUS-112",
    assignedDriverId: "drv-4",
    assignedDriverName: "David Miller",
    assignedAideId: undefined,
    studentsCount: 24,
    stopsCount: 5,
    startTime: "07:25 AM",
    expectedArrival: "08:05 AM",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "delayed",
    description: "Connects Eastern residential district. Experiencing brief utility delay.",
    stops: [
      { id: "st-41", name: "Highland Greens", address: "20 Greens Way", scheduledTime: "07:30 AM", studentsCount: 6, status: "departed", order: 1 },
      { id: "st-42", name: "Cypress Point", address: "140 Cypress Dr", scheduledTime: "07:39 AM", studentsCount: 8, status: "departed", order: 2 },
      { id: "st-43", name: "Fullerton Crossing", address: "550 Fullerton St", scheduledTime: "07:48 AM", studentsCount: 6, status: "delayed", order: 3 },
      { id: "st-44", name: "Sycamore Square", address: "302 Sycamore Ct", scheduledTime: "07:56 AM", studentsCount: 4, status: "upcoming", order: 4 },
      { id: "st-45", name: "Lincoln School — Main Dropoff", address: "742 Evergreen Terrace", scheduledTime: "08:05 AM", studentsCount: 0, status: "upcoming", order: 5 },
    ],
  },
  {
    id: "rt-5",
    routeNumber: "Route 14",
    name: "East Meadow Shuttle",
    schoolId: "sch-1",
    assignedVehicleId: "veh-5",
    assignedVehicleNumber: "VAN-201",
    assignedDriverId: "drv-5",
    assignedDriverName: "Sarah Jenkins",
    assignedAideId: "aid-4",
    assignedAideName: "Chloe Bennett",
    studentsCount: 12,
    stopsCount: 3,
    startTime: "07:35 AM",
    expectedArrival: "08:05 AM",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    status: "scheduled",
    description: "Specialized small-group shuttle service with dedicated aide assistance.",
    stops: [
      { id: "st-51", name: "Meadow View Community", address: "70 Meadow View", scheduledTime: "07:40 AM", studentsCount: 4, status: "upcoming", order: 1 },
      { id: "st-52", name: "Sunflower Court", address: "18 Sunflower Ct", scheduledTime: "07:50 AM", studentsCount: 4, status: "upcoming", order: 2 },
      { id: "st-53", name: "Lincoln School — Accessible Entry", address: "742 Evergreen Terrace", scheduledTime: "08:05 AM", studentsCount: 4, status: "upcoming", order: 3 },
    ],
  },
];

export const initialDrivers: Driver[] = [
  {
    id: "drv-1",
    name: "Ahmed Khan",
    email: "ahmed.khan@auratransit.net",
    phone: "+1 (312) 555-0131",
    licenseNumber: "CDL-IL-849203",
    licenseExpiry: "2027-11-15",
    assignedVehicleId: "veh-1",
    assignedVehicleNumber: "BUS-104",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    schoolId: "sch-1",
    tripsCount: 412,
    rating: 4.96,
    status: "on_trip",
  },
  {
    id: "drv-2",
    name: "Marcus Vance",
    email: "m.vance@auratransit.net",
    phone: "+1 (312) 555-0142",
    licenseNumber: "CDL-IL-774921",
    licenseExpiry: "2028-04-10",
    assignedVehicleId: "veh-2",
    assignedVehicleNumber: "BUS-108",
    assignedRouteId: "rt-2",
    assignedRouteName: "Route 04 · North Loop",
    schoolId: "sch-1",
    tripsCount: 388,
    rating: 4.92,
    status: "on_trip",
  },
  {
    id: "drv-3",
    name: "Elena Rostova",
    email: "e.rostova@auratransit.net",
    phone: "+1 (312) 555-0153",
    licenseNumber: "CDL-IL-663819",
    licenseExpiry: "2027-08-22",
    assignedVehicleId: "veh-3",
    assignedVehicleNumber: "BUS-101",
    assignedRouteId: "rt-3",
    assignedRouteName: "Route 01 · South Hill",
    schoolId: "sch-1",
    tripsCount: 520,
    rating: 4.98,
    status: "on_trip",
  },
  {
    id: "drv-4",
    name: "David Miller",
    email: "d.miller@auratransit.net",
    phone: "+1 (312) 555-0164",
    licenseNumber: "CDL-IL-552910",
    licenseExpiry: "2026-10-05",
    assignedVehicleId: "veh-4",
    assignedVehicleNumber: "BUS-112",
    assignedRouteId: "rt-4",
    assignedRouteName: "Route 12 · Highland Park",
    schoolId: "sch-1",
    tripsCount: 295,
    rating: 4.88,
    status: "on_trip",
  },
  {
    id: "drv-5",
    name: "Sarah Jenkins",
    email: "s.jenkins@auratransit.net",
    phone: "+1 (312) 555-0175",
    licenseNumber: "CDL-IL-441829",
    licenseExpiry: "2028-02-18",
    assignedVehicleId: "veh-5",
    assignedVehicleNumber: "VAN-201",
    assignedRouteId: "rt-5",
    assignedRouteName: "Route 14 · East Meadow",
    schoolId: "sch-1",
    tripsCount: 180,
    rating: 4.95,
    status: "active",
  },
  {
    id: "drv-6",
    name: "Carlos Mendez",
    email: "c.mendez@auratransit.net",
    phone: "+1 (312) 555-0186",
    licenseNumber: "CDL-IL-330748",
    licenseExpiry: "2027-06-30",
    assignedVehicleId: "veh-6",
    assignedVehicleNumber: "EV-301",
    schoolId: "sch-1",
    tripsCount: 340,
    rating: 4.91,
    status: "off_duty",
  },
];

export const initialAides: Aide[] = [
  {
    id: "aid-1",
    name: "Maria Santos",
    email: "m.santos@lincoln.edu",
    phone: "+1 (312) 555-0211",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    assignedVehicleId: "veh-1",
    assignedVehicleNumber: "BUS-104",
    schoolId: "sch-1",
    status: "on_duty",
    certification: "Pediatric First Aid & Student Safety Cert (Exp 2027)",
  },
  {
    id: "aid-2",
    name: "Brenda Walsh",
    email: "b.walsh@lincoln.edu",
    phone: "+1 (312) 555-0222",
    assignedRouteId: "rt-2",
    assignedRouteName: "Route 04 · North Loop",
    assignedVehicleId: "veh-2",
    assignedVehicleNumber: "BUS-108",
    schoolId: "sch-1",
    status: "on_duty",
    certification: "Specialized Mobility Aide Cert II (Exp 2028)",
  },
  {
    id: "aid-3",
    name: "James Lee",
    email: "j.lee@lincoln.edu",
    phone: "+1 (312) 555-0233",
    assignedRouteId: "rt-3",
    assignedRouteName: "Route 01 · South Hill",
    assignedVehicleId: "veh-3",
    assignedVehicleNumber: "BUS-101",
    schoolId: "sch-1",
    status: "on_duty",
    certification: "Standard Transportation Aide Cert (Exp 2026)",
  },
  {
    id: "aid-4",
    name: "Chloe Bennett",
    email: "c.bennett@lincoln.edu",
    phone: "+1 (312) 555-0244",
    assignedRouteId: "rt-5",
    assignedRouteName: "Route 14 · East Meadow",
    assignedVehicleId: "veh-5",
    assignedVehicleNumber: "VAN-201",
    schoolId: "sch-1",
    status: "active",
    certification: "Pediatric First Aid & Non-Violent Crisis Intervention",
  },
];

export const initialParents: Parent[] = [
  {
    id: "par-1",
    name: "Michael & Sarah Johnson",
    email: "sarah.johnson@example.com",
    phone: "+1 (312) 555-0311",
    schoolId: "sch-1",
    studentIds: ["stu-1"],
    studentNames: ["Emma Johnson"],
    assignedRouteNames: ["Route 08 · West Valley"],
    notificationStatus: "sms_and_app",
    pickupAddress: "402 Maple Ave, Chicago, IL",
    status: "active",
  },
  {
    id: "par-2",
    name: "David & Rachel Patel",
    email: "rachel.patel@example.com",
    phone: "+1 (312) 555-0322",
    schoolId: "sch-1",
    studentIds: ["stu-2"],
    studentNames: ["Noah Patel"],
    assignedRouteNames: ["Route 08 · West Valley"],
    notificationStatus: "sms_and_app",
    pickupAddress: "128 Cedar Hill Rd, Chicago, IL",
    status: "active",
  },
  {
    id: "par-3",
    name: "Linda Chen",
    email: "linda.chen@example.com",
    phone: "+1 (312) 555-0333",
    schoolId: "sch-1",
    studentIds: ["stu-3"],
    studentNames: ["Lucas Chen"],
    assignedRouteNames: ["Route 04 · North Loop"],
    notificationStatus: "app_only",
    pickupAddress: "550 Pinewood Rd, Chicago, IL",
    status: "active",
  },
  {
    id: "par-4",
    name: "Robert & Emily Taylor",
    email: "e.taylor@example.com",
    phone: "+1 (312) 555-0344",
    schoolId: "sch-1",
    studentIds: ["stu-4"],
    studentNames: ["Maya Taylor"],
    assignedRouteNames: ["Route 01 · South Hill"],
    notificationStatus: "sms_and_app",
    pickupAddress: "12 Brookside Way, Chicago, IL",
    status: "active",
  },
  {
    id: "par-5",
    name: "Anthony Diaz",
    email: "anthony.diaz@example.com",
    phone: "+1 (312) 555-0355",
    schoolId: "sch-1",
    studentIds: ["stu-5"],
    studentNames: ["Sophia Diaz"],
    assignedRouteNames: ["Route 12 · Highland Park"],
    notificationStatus: "sms_only",
    pickupAddress: "20 Greens Way, Chicago, IL",
    status: "active",
  },
];

export const initialStudents: Student[] = [
  {
    id: "stu-1",
    firstName: "Emma",
    lastName: "Johnson",
    studentId: "STU-2026-041",
    grade: "5th Grade",
    schoolId: "sch-1",
    parentId: "par-1",
    parentName: "Michael & Sarah Johnson",
    emergencyContact: "+1 (312) 555-0311 (Mother)",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    pickupStopName: "Maple Ave & 4th",
    status: "on_board",
    allergiesOrNotes: "Carries asthma inhaler",
  },
  {
    id: "stu-2",
    firstName: "Noah",
    lastName: "Patel",
    studentId: "STU-2026-088",
    grade: "4th Grade",
    schoolId: "sch-1",
    parentId: "par-2",
    parentName: "David & Rachel Patel",
    emergencyContact: "+1 (312) 555-0322 (Father)",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    pickupStopName: "Cedar Hill Community Center",
    status: "on_board",
  },
  {
    id: "stu-3",
    firstName: "Lucas",
    lastName: "Chen",
    studentId: "STU-2026-102",
    grade: "6th Grade",
    schoolId: "sch-1",
    parentId: "par-3",
    parentName: "Linda Chen",
    emergencyContact: "+1 (312) 555-0333 (Mother)",
    assignedRouteId: "rt-2",
    assignedRouteName: "Route 04 · North Loop",
    pickupStopName: "Pinewood Estates",
    status: "on_board",
  },
  {
    id: "stu-4",
    firstName: "Maya",
    lastName: "Taylor",
    studentId: "STU-2026-154",
    grade: "3rd Grade",
    schoolId: "sch-1",
    parentId: "par-4",
    parentName: "Robert & Emily Taylor",
    emergencyContact: "+1 (312) 555-0344 (Mother)",
    assignedRouteId: "rt-3",
    assignedRouteName: "Route 01 · South Hill",
    pickupStopName: "Brookside Commons",
    status: "on_board",
    allergiesOrNotes: "Peanut allergy",
  },
  {
    id: "stu-5",
    firstName: "Sophia",
    lastName: "Diaz",
    studentId: "STU-2026-210",
    grade: "7th Grade",
    schoolId: "sch-1",
    parentId: "par-5",
    parentName: "Anthony Diaz",
    emergencyContact: "+1 (312) 555-0355 (Father)",
    assignedRouteId: "rt-4",
    assignedRouteName: "Route 12 · Highland Park",
    pickupStopName: "Highland Greens",
    status: "active",
  },
  {
    id: "stu-6",
    firstName: "Liam",
    lastName: "Walker",
    studentId: "STU-2026-245",
    grade: "5th Grade",
    schoolId: "sch-1",
    parentId: "par-1",
    parentName: "Michael & Sarah Johnson",
    emergencyContact: "+1 (312) 555-0311",
    assignedRouteId: "rt-1",
    assignedRouteName: "Route 08 · West Valley",
    pickupStopName: "Grand Ave & Elm St",
    status: "active",
  },
  {
    id: "stu-7",
    firstName: "Olivia",
    lastName: "Garcia",
    studentId: "STU-2026-289",
    grade: "2nd Grade",
    schoolId: "sch-1",
    parentId: "par-2",
    parentName: "David & Rachel Patel",
    emergencyContact: "+1 (312) 555-0322",
    assignedRouteId: "rt-5",
    assignedRouteName: "Route 14 · East Meadow",
    pickupStopName: "Meadow View Community",
    status: "active",
  },
  {
    id: "stu-8",
    firstName: "Ethan",
    lastName: "Brown",
    studentId: "STU-2026-302",
    grade: "8th Grade",
    schoolId: "sch-1",
    parentId: "par-3",
    parentName: "Linda Chen",
    emergencyContact: "+1 (312) 555-0333",
    assignedRouteId: "rt-2",
    assignedRouteName: "Route 04 · North Loop",
    pickupStopName: "Lakeland Library",
    status: "dropped_off",
  },
];

export const initialUsers: User[] = [
  {
    id: "usr-1",
    name: "Dr. Julian Hayes",
    email: "j.hayes@lincoln.edu",
    phone: "+1 (312) 555-0192",
    role: "school_admin",
    schoolId: "sch-1",
    schoolName: "Lincoln International School",
    status: "active",
    lastActive: "Just now",
    createdAt: "2025-08-15",
  },
  {
    id: "usr-2",
    name: "Priya Patel",
    email: "p.patel@lincoln.edu",
    phone: "+1 (312) 555-0193",
    role: "transportation_manager",
    schoolId: "sch-1",
    schoolName: "Lincoln International School",
    status: "active",
    lastActive: "5 mins ago",
    createdAt: "2025-08-20",
  },
  {
    id: "usr-3",
    name: "Samira Al-Mansoor",
    email: "samira.ops@lincoln.edu",
    phone: "+1 (312) 555-0194",
    role: "dispatcher",
    schoolId: "sch-1",
    schoolName: "Lincoln International School",
    status: "active",
    lastActive: "2 mins ago",
    createdAt: "2025-09-01",
  },
  {
    id: "usr-4",
    name: "Kevin Ortiz",
    email: "k.ortiz@lincoln.edu",
    phone: "+1 (312) 555-0195",
    role: "staff",
    schoolId: "sch-1",
    schoolName: "Lincoln International School",
    status: "active",
    lastActive: "1 hour ago",
    createdAt: "2025-09-15",
  },
  {
    id: "usr-sup-1",
    name: "AuraTransit Platform Director",
    email: "admin@auratransit.com",
    phone: "+1 (800) 555-0100",
    role: "super_admin",
    status: "active",
    lastActive: "Just now",
    createdAt: "2025-01-01",
  },
];

export const initialTrips: TripHistoryItem[] = [
  {
    id: "trp-9021",
    tripNumber: "TRP-9021",
    date: "Today, Mar 24, 2026",
    routeId: "rt-1",
    routeName: "Route 08 · West Valley",
    vehicleId: "veh-1",
    vehicleNumber: "BUS-104",
    driverId: "drv-1",
    driverName: "Ahmed Khan",
    studentsCount: 28,
    startTime: "07:15 AM",
    arrivalTime: "07:54 AM",
    durationMinutes: 39,
    status: "in_progress",
    notes: "Normal morning commute. Weather clear.",
    delaysReported: 0,
    events: [
      { time: "07:15 AM", description: "Departed school depot on schedule", type: "departure" },
      { time: "07:18 AM", description: "Stop 1: Maple Ave & 4th (5 boarded)", type: "stop" },
      { time: "07:25 AM", description: "Stop 2: Cedar Hill (6 boarded)", type: "stop" },
      { time: "07:33 AM", description: "Stop 3: West Gate Crossing (7 boarded)", type: "stop" },
    ],
  },
  {
    id: "trp-9022",
    tripNumber: "TRP-9022",
    date: "Today, Mar 24, 2026",
    routeId: "rt-2",
    routeName: "Route 04 · North Loop",
    vehicleId: "veh-2",
    vehicleNumber: "BUS-108",
    driverId: "drv-2",
    driverName: "Marcus Vance",
    studentsCount: 32,
    startTime: "07:10 AM",
    arrivalTime: "07:49 AM",
    durationMinutes: 39,
    status: "in_progress",
    notes: "All morning stops completed smoothly.",
    delaysReported: 0,
    events: [
      { time: "07:10 AM", description: "Departed North Depot", type: "departure" },
      { time: "07:16 AM", description: "Stop 1: Pinewood Estates (8 boarded)", type: "stop" },
      { time: "07:26 AM", description: "Stop 2: Lakeland Library (9 boarded)", type: "stop" },
    ],
  },
  {
    id: "trp-9023",
    tripNumber: "TRP-9023",
    date: "Today, Mar 24, 2026",
    routeId: "rt-4",
    routeName: "Route 12 · Highland Park",
    vehicleId: "veh-4",
    vehicleNumber: "BUS-112",
    driverId: "drv-4",
    driverName: "David Miller",
    studentsCount: 24,
    startTime: "07:25 AM",
    arrivalTime: "08:11 AM",
    durationMinutes: 46,
    status: "delayed",
    notes: "Utility lane closure on Fullerton Parkway caused a 6-minute delay.",
    delaysReported: 1,
    events: [
      { time: "07:25 AM", description: "Departed Depot", type: "departure" },
      { time: "07:31 AM", description: "Stop 1: Highland Greens (6 boarded)", type: "stop" },
      { time: "07:48 AM", description: "Slow traffic reported at Fullerton Crossing", type: "incident" },
    ],
  },
  {
    id: "trp-9020",
    tripNumber: "TRP-9020",
    date: "Yesterday, Mar 23, 2026",
    routeId: "rt-1",
    routeName: "Route 08 · West Valley",
    vehicleId: "veh-1",
    vehicleNumber: "BUS-104",
    driverId: "drv-1",
    driverName: "Ahmed Khan",
    studentsCount: 28,
    startTime: "03:15 PM",
    arrivalTime: "03:53 PM",
    durationMinutes: 38,
    status: "completed",
    notes: "Afternoon drop-offs all verified with contactless scan.",
    delaysReported: 0,
  },
  {
    id: "trp-9019",
    tripNumber: "TRP-9019",
    date: "Yesterday, Mar 23, 2026",
    routeId: "rt-3",
    routeName: "Route 01 · South Hill",
    vehicleId: "veh-3",
    vehicleNumber: "BUS-101",
    driverId: "drv-3",
    driverName: "Elena Rostova",
    studentsCount: 20,
    startTime: "03:20 PM",
    arrivalTime: "03:57 PM",
    durationMinutes: 37,
    status: "completed",
    notes: "On time arrival at South Loop.",
    delaysReported: 0,
  },
];

export const initialSubscription: Subscription = {
  plan: "Enterprise",
  status: "active",
  renewalDate: "August 15, 2026",
  vehiclesLimit: 15,
  vehiclesUsed: 8,
  studentsLimit: 500,
  studentsUsed: 348,
  monthlyAmount: 849,
};

export const initialInvoices: Invoice[] = [
  { id: "inv-101", number: "INV-2026-03", date: "Mar 01, 2026", amount: 849, status: "paid" },
  { id: "inv-100", number: "INV-2026-02", date: "Feb 01, 2026", amount: 849, status: "paid" },
  { id: "inv-099", number: "INV-2026-01", date: "Jan 01, 2026", amount: 849, status: "paid" },
  { id: "inv-098", number: "INV-2025-12", date: "Dec 01, 2025", amount: 849, status: "paid" },
];
